# Generated by Django 5.2 on 2025-05-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestExample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('created_ad', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Example',
                'verbose_name_plural': 'Examples',
            },
        ),
    ]
