# Generated by Django 5.2 on 2025-05-07 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testexample',
            old_name='created_ad',
            new_name='created_at',
        ),
    ]
