# Generated by Django 5.2 on 2025-05-24 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subtask",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
