# Generated by Django 5.2 on 2025-05-24 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_subtask_updated_at"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="deadline",
        ),
    ]
