# Generated by Django 5.2 on 2025-05-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_project_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subtask",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("in_qa", "In QA"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    ("todo", "To Do"),
                    ("in_progress", "In Progress"),
                    ("in_review", "In Review"),
                    ("in_qa", "In QA"),
                    ("rejected", "Rejected"),
                    ("canceled", "Canceled"),
                    ("done", "Done"),
                ],
                default="todo",
                max_length=20,
            ),
        ),
    ]
